2025-04-29 03:55:57,171 WARNING: Google Earth Engine n'a pas pu être initialisé [in /app/app/__init__.py:48]
2025-04-29 08:44:55,433 INFO: Application démarrée [in /app/app/__init__.py:41]
2025-04-29 08:44:55,433 INFO: Application démarrée [in /app/app/__init__.py:41]
2025-04-29 08:44:55,440 INFO: Application démarrée [in /app/app/__init__.py:41]
2025-04-29 08:44:55,450 INFO: Application démarrée [in /app/app/__init__.py:41]
2025-04-29 08:45:11,617 INFO: Google Earth Engine initialisé avec succès [in /app/app/gee_utils.py:53]
2025-04-29 08:45:11,718 INFO: Google Earth Engine initialisé avec succès [in /app/app/gee_utils.py:53]
2025-04-29 08:45:12,978 INFO: Google Earth Engine initialisé avec succès [in /app/app/gee_utils.py:53]
2025-04-29 08:45:13,014 INFO: Google Earth Engine initialisé avec succès [in /app/app/gee_utils.py:53]
2025-04-29 09:53:31,810 ERROR: Erreur lors de la création de la carte avec série temporelle: ts_inspector() missing 3 required positional arguments: 'right_ts', 'left_names', and 'right_names' [in /app/app/gee_utils.py:263]
2025-04-29 09:53:31,834 ERROR: Erreur lors de l'analyse: ts_inspector() missing 3 required positional arguments: 'right_ts', 'left_names', and 'right_names' [in /app/app/routes.py:127]
2025-04-29 09:55:44,221 ERROR: Erreur lors de la création de la carte avec série temporelle: ts_inspector() missing 3 required positional arguments: 'right_ts', 'left_names', and 'right_names' [in /app/app/gee_utils.py:263]
2025-04-29 09:55:44,228 ERROR: Erreur lors de l'analyse: ts_inspector() missing 3 required positional arguments: 'right_ts', 'left_names', and 'right_names' [in /app/app/routes.py:127]
2025-04-29 10:01:43,232 ERROR: Erreur lors de la création de la carte avec série temporelle: ts_inspector() missing 3 required positional arguments: 'right_ts', 'left_names', and 'right_names' [in /app/app/gee_utils.py:263]
2025-04-29 10:01:43,256 ERROR: Erreur lors de l'analyse: ts_inspector() missing 3 required positional arguments: 'right_ts', 'left_names', and 'right_names' [in /app/app/routes.py:127]
2025-04-29 10:12:04,249 INFO: Application démarrée [in /app/app/__init__.py:41]
2025-04-29 10:12:04,252 INFO: Application démarrée [in /app/app/__init__.py:41]
2025-04-29 10:12:04,252 INFO: Application démarrée [in /app/app/__init__.py:41]
2025-04-29 10:12:04,252 INFO: Application démarrée [in /app/app/__init__.py:41]
2025-04-29 10:12:20,600 INFO: Google Earth Engine initialisé avec succès [in /app/app/gee_utils.py:53]
2025-04-29 10:12:22,194 INFO: Google Earth Engine initialisé avec succès [in /app/app/gee_utils.py:53]
2025-04-29 10:12:23,329 INFO: Google Earth Engine initialisé avec succès [in /app/app/gee_utils.py:53]
2025-04-29 10:12:23,357 INFO: Google Earth Engine initialisé avec succès [in /app/app/gee_utils.py:53]
2025-04-29 10:13:09,621 ERROR: Erreur lors de la création de la carte avec série temporelle: ts_inspector() missing 3 required positional arguments: 'right_ts', 'left_names', and 'right_names' [in /app/app/gee_utils.py:263]
2025-04-29 10:13:09,624 ERROR: Erreur lors de l'analyse: ts_inspector() missing 3 required positional arguments: 'right_ts', 'left_names', and 'right_names' [in /app/app/routes.py:127]
2025-04-29 10:13:28,119 ERROR: Erreur lors de la création de la carte avec série temporelle: ts_inspector() missing 3 required positional arguments: 'right_ts', 'left_names', and 'right_names' [in /app/app/gee_utils.py:263]
2025-04-29 10:13:28,121 ERROR: Erreur lors de l'analyse: ts_inspector() missing 3 required positional arguments: 'right_ts', 'left_names', and 'right_names' [in /app/app/routes.py:127]
2025-04-29 11:13:52,596 INFO: Application démarrée [in /app/app/__init__.py:41]
2025-04-29 11:13:52,597 INFO: Application démarrée [in /app/app/__init__.py:41]
2025-04-29 11:13:52,597 INFO: Application démarrée [in /app/app/__init__.py:41]
2025-04-29 11:13:52,682 INFO: Application démarrée [in /app/app/__init__.py:41]
2025-04-29 11:14:07,723 INFO: Google Earth Engine initialisé avec succès [in /app/app/gee_utils.py:53]
2025-04-29 11:14:09,659 INFO: Google Earth Engine initialisé avec succès [in /app/app/gee_utils.py:53]
2025-04-29 11:14:10,903 INFO: Google Earth Engine initialisé avec succès [in /app/app/gee_utils.py:53]
2025-04-29 11:14:11,327 INFO: Google Earth Engine initialisé avec succès [in /app/app/gee_utils.py:53]
2025-04-29 11:15:10,772 ERROR: Erreur lors de la création de la carte avec série temporelle: Image.visualize: Cannot provide a palette when visualizing more than one band. [in /app/app/gee_utils.py:270]
2025-04-29 11:15:10,778 ERROR: Erreur lors de l'analyse: Image.visualize: Cannot provide a palette when visualizing more than one band. [in /app/app/routes.py:127]
